### ISSUE TITLE
No Jobs Found

### ISSUE THREAD

**Issue by jetnet** [Norconex/jef-monitor#10]
a silly question - does JEF monitor work on Windows?
I'm asking, because I'm getting the "no jobs found" message, when I point JEF to the crawler's `progress\latest` directory, which is containing one "`<httpcollector_id>.index`" file.

Not sure, if the following is related, but JEF (4.0.5) is throwing an exception when started:
```
Exception in thread "Thread-10" com.norconex.commons.lang.config.ConfigurationException: This class could not be instantiated: "com.norconex.jef4.log.NoLogManager".
        at com.norconex.commons.lang.config.XMLConfigurationUtil.newInstance(XMLConfigurationUtil.java:192)
        at com.norconex.commons.lang.config.XMLConfigurationUtil.newInstance(XMLConfigurationUtil.java:273)
        at com.norconex.commons.lang.config.XMLConfigurationUtil.newInstance(XMLConfigurationUtil.java:233)
        at com.norconex.jef4.status.JobSuiteStatusSnapshot.newSnapshot(JobSuiteStatusSnapshot.java:188)
        at com.norconex.jefmon.instance.JEFMonInstance$Monitor.syncIndexFiles(JEFMonInstance.java:143)
        at com.norconex.jefmon.instance.JEFMonInstance$Monitor.run(JEFMonInstance.java:112)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.norconex.jef4.log.NoLogManager
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at com.norconex.commons.lang.config.XMLConfigurationUtil.newInstance(XMLConfigurationUtil.java:190)
        ... 6 more
```

**Comment by essiembre** [comment]
Yes it does.  JEF uses the log manager defined in your collector to offer the ability to view logs.

In your case, you are using the snapshot version that has ``com.norconex.jef4.log.NoLogManager``.  That class is not found in JEF Monitor class path.  So the solution is to replace the ``norconex-jef.jar`` found in JEF Monitor lib directory with the snapshot version of JEF API.

**Comment by jetnet** [comment]
Thanks, Pascal!
upgrading to {{norconex-jef-4.1.2-20190419.210227-1.jar}} helped - no exception and the job is displayed now!

FYI: I was using a version from https://www.norconex.com/jef/monitor/ - it was not marked as a snapshot one. Maybe the link is not correct.

**Comment by essiembre** [comment]
Thanks for reporting this.  There is now a snapshot version of JEF Monitor that is in sync with the JEF API snapshot.
